<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Graduation List — {{ $academicYear->start_year }}-{{ $academicYear->end_year }} {{ $semester->term->label() }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; }
        h1 { font-size: 16px; margin-bottom: 2px; }
        .header { text-align: center; margin-bottom: 16px; }
        .muted { color: #64748b; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
        th, td { border: 1px solid #cbd5e1; padding: 4px 6px; text-align: left; font-size: 10px; }
        th { background: #f1f5f9; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 8px; font-size: 9px; text-transform: uppercase; background: #e2e8f0; }
        .footer { margin-top: 24px; font-size: 9px; color: #94a3b8; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $college->name }}</h1>
        <p class="muted">Graduation List — {{ $academicYear->start_year }}-{{ $academicYear->end_year }} {{ $semester->term->label() }}</p>
    </div>

    @if ($candidates->isEmpty())
        <p class="muted">No approved or graduated candidates found for this term{{ $department ? " in {$department->name}" : '' }}.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Student No.</th>
                    <th>Name</th>
                    <th>Department</th>
                    <th>Program</th>
                    <th>GWA</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($candidates as $i => $candidate)
                    <tr>
                        <td>{{ $i + 1 }}</td>
                        <td>{{ $candidate->student->student_number }}</td>
                        <td>{{ $candidate->student->first_name }} {{ $candidate->student->middle_name }} {{ $candidate->student->surname }}</td>
                        <td>{{ $candidate->student->department?->name }}</td>
                        <td>{{ $candidate->student->program?->name }}</td>
                        <td>{{ $candidate->gwa_snapshot ?? '—' }}</td>
                        <td><span class="badge">{{ $candidate->status->value }}</span></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <p class="muted">{{ $candidates->count() }} candidate{{ $candidates->count() === 1 ? '' : 's' }}.</p>
    @endif

    <div class="footer">
        Generated by {{ $generatedBy->name }} on {{ now()->format('F j, Y g:i A') }} — CA-APOMS
    </div>
</body>
</html>
