<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; }
        h1 { font-size: 16px; margin-bottom: 2px; }
        .header { text-align: center; margin-bottom: 16px; }
        .muted { color: #64748b; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
        th, td { border: 1px solid #cbd5e1; padding: 4px 6px; text-align: left; font-size: 10px; }
        th { background: #f1f5f9; }
        .footer { margin-top: 24px; font-size: 9px; color: #94a3b8; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $college->name }}</h1>
        <p class="muted">{{ $title }} &mdash; {{ $scopeDescription }}</p>
    </div>

    @if (empty($rows))
        <p class="muted">No data found for this selection.</p>
    @else
        <table>
            <thead>
                <tr>
                    @foreach ($headings as $heading)
                        <th>{{ $heading }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($rows as $row)
                    <tr>
                        @foreach ($row as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
        <p class="muted">{{ count($rows) }} row{{ count($rows) === 1 ? '' : 's' }}.</p>
    @endif

    <div class="footer">
        Generated by {{ $generatedBy->name }} on {{ now()->format('F j, Y g:i A') }} &mdash; CA-APOMS
    </div>
</body>
</html>
